name: Update DNS & SSL Certificate

on:
  schedule:
  - cron: '0/30 * * * *'

env:
  FUNCTIONAPP_PATH: 'src/DevRelKr.UrlShortener.FunctionApp'

jobs:
  update_dns_and_ssl_certificate:
    name: 'PROD: Update DNS and SSL Certificate'

    runs-on: ubuntu-latest

    steps:
    - name: Update A Record
      shell: pwsh
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_PROD }}
      run: |
        ./scripts/Update-AzDnsARecord.ps1 -AppResourceGroupName ${{ secrets.RESOURCE_GROUP_NAME_PROD }} -AppName ${{ secrets.RESOURCE_FUNCTIONAPP_NAME_PROD }} -ZoneResourceGroupName ${{ secrets.RESOURCE_GROUP_NAME_ZONE }} -ZoneName ${{ secrets.RESOURCE_NAME_ZONE }}

    - name: Update SSL Certificate
      shell: pwsh
      run: |
        ./scripts/Update-AzSslCertificate.ps1 -ApiEndpoint ${{ secrets.SSL_RENEW_ENDPOINT }} -DnsNames ${{ secrets.SSL_DNS_NAMES }}
